### ISSUE TITLE
[v66] cannot kill ghost, found this is a config issue

### ISSUE THREAD

**Issue by CoolLKKPS** [LouisSilva/LethalCompanyHauntedHarpist#15]
@LouisSilva u cannot hit the ghost by using shovel, use dev mode and u will know

**Comment by LouisSilva** [comment]
Thanks, I'll look into it later.

**Comment by CoolLKKPS** [comment]
@LouisSilva if disable `Friendly Fire`, any source dmg won't be apply, and i think that's a little big problem

**Comment by LouisSilva** [comment]
> @LouisSilva if disable `Friendly Fire`, any source dmg won't be apply, and i think that's a little big problem

If friendly fire is turned off, then the ghost wont take damage from anything other than players.

**Comment by CoolLKKPS** [comment]
hmm weird the config say won't take monster dmg..

**Comment by LouisSilva** [comment]
> hmm weird the config say won't take monster dmg..

Nah the config description says: "Whether the Haunted Harpist can be killed by **something other than a player** e.g. an eyeless dog". Sorry if that's a bit misleading.

I should note that because of the way enemies are coded, an enemy can only tell whether it took damage from a player, there is no other information given to determine the attacker. 

There is also a very possible edge case where a player may be firing a rocket launcher (a weapon from a mod) at an enemy, which propels the rocket projectile at the enemy, and that projectile is what does the damage, not the rocket launcher itself. The modder may then call the enemies `IHittable.Hit(int force, Vector3 hitDirection, PlayerControllerB playerWhoHit = null, bool playHitSFX = false, int hitID = -1)` function from the projectile object, without filling in the `playerWhoHit` parameter. This would cause the Harpist to say "Well, that rocket wasn't fired from a player, so I take no damage...".

That isn't *supposed* to happen, because they obviously should give the projectile object a reference to the player who fired the rocket launcher and use it in the `IHittable.Hit` function, but accidents happen, and this is only one example of the many edge cases that can arise from this.

I will add a warning in the config saying that it *may* be incompatible with some mods.

**Comment by CoolLKKPS** [comment]
oh.. i did forgot report some bug and send my opinion to u
so first, i did sug improve friendly fire option, bc in my first time i actually think that will cause ghost can trigger the landmine, so can u make 2 options change, first the ghost only can be killed when takes enough more hits, just like maneater, and second i don't like the ghost can trigger or takes the hazard dmg
now the second issue, did u notice the harp are always dropped when harpghost spawned? unlike nutcracker, u can pickup harp without aggro the ghost

i think u got a lot the work need to be done now.

**Comment by LouisSilva** [comment]
> now the second issue, did u notice the harp are always dropped when harpghost spawned? unlike nutcracker, u can pickup harp without aggro the ghost


In the new update (commit 3d3c184), the issue with the ghost dropping the harp upon spawning is fixed.


> i don't like the ghost can trigger or takes the hazard dmg


The ghost can only trigger a hazard if you have another mod which is causing it. No enemies in the base game can trigger hazards.


> first the ghost only can be killed when takes enough more hits


You can change the amount of health the ghost has in the config. I personally think that a HP of 4 is the best, but obviously thats just my opinion; you are free to set it to whatever you wish.

I'm going to close this issue now because its been resolved, thank you for reporting the bugs :)
